logger_name: "s3replicator"

file:
   path: "/var/log/seagate/s3/replication/replicator/"
   log_filename: "s3replicator.log"
   log_level: INFO  # https://docs.python.org/3/library/logging.html#levels
   log_format: '%(asctime)s [%(levelname)s] [%(filename)s: %(lineno)d] %(message)s'
   max_size_in_bytes: 5242880 # 5MB
   backup_count: 5    # Max 5 log files created and rotated

console:
   enabled: true
   log_level: DEBUG  # https://docs.python.org/3/library/logging.html#levels
   log_format: '%(asctime)s [%(levelname)s] [%(filename)s: %(lineno)d] %(message)s'